
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms

"""


def fib():
    memo = [1,2]
    last = 2
    while memo[last-1] < 4000000:
            memo.insert(last, memo[last-1]+memo[last-2])
            last += 1
    return sum(filter(lambda x: x % 2 == 0, memo))
            
