#!/usr/bin/perl

use 5.010;
use autodie;
use strict;
use utf8;

=begin comment

The sum of the squares of the first ten natural numbers is,

12 + 22 + ... + 102 = 385
The square of the sum of the first ten natural numbers is,

(1 + 2 + ... + 10)2 = 552 = 3025
Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.

Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.

=cut

sub sum_of_squares { 
    my $x = shift;
    my $sum = 0;
    foreach (1..$x){
        $sum += $_**2;
    }
    return $sum;
}

sub square_of_sums {
    my $x = shift;
    my $sum = 0;
    foreach (1..$x){
        $sum += $_;
    }
    return $sum**2;
}

say square_of_sums(100) - sum_of_squares(100);



