#!/usr/bin/perl

use 5.010;
use strict;

=begin comment

A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,

a2 + b2 = c2
For example, 32 + 42 = 9 + 16 = 25 = 52.

There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

=cut


sub pyth_trip { 
    
    foreach my $a (1...999){
        foreach my $b (($a+1)..999){
            my $c = 1000 - $a - $b;
            if ($c**2 == ($b**2 + $a**2)){
                return $a*$b*$c;
            }
        }
    }

}

say pyth_trip();

        

